name: "Meta Reports 7"
on:
  schedule:
    - cron: '0 5,6,7,8,17,18,19,20 * * *'
  push:
    branches:
      - main
      
jobs:
  update-google-reports:
    name: Update Meta Reports
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    steps:
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - name: Setup - Checkout repo
        uses: actions/checkout@v3
      - name: Apt-get update things
        run: |
          sudo apt-get update 
      - name: Apt-get needed things
        run: |
          sudo apt-get install --no-install-recommends -y \
          libssl-dev \
          libcurl4-openssl-dev \
          libxml2-dev \
          libharfbuzz-dev \
          libfribidi-dev
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'  # Choose the appropriate Node.js version

      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: "Check Playwright CLI"
        run: npx playwright --version
      - name: "Script - Meta Run"
        run: Rscript 'reports.R' "last_7_days"
