name: Get Targeting Data

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Get Targeting Data"]
    types:
      - completed
  push:
    branches:
      - main
      
jobs:
  update-seven-targets:
    name: Update Seven Targets
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - name: Setup - Checkout repo
        uses: actions/checkout@v3
      - name: Apt-get needed things
        run: |
          sudo apt-get install --no-install-recommends -y \
          libssl-dev \
          libcurl4-openssl-dev \
          libxml2-dev \
          libharfbuzz-dev \
          libfribidi-dev
      - run: echo "🍏 This job's status is ${{ job.status }}."

      - name: "Install Packages"
        run: |
          install.packages('pacman')
        shell: Rscript {0}
      - name: "Script - Run"
        run: Rscript 'get.R'


      - name: "Commit"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Retrieve Seven Reports